name: maps_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  animate_do: ^3.1.2
  bloc: ^8.1.2
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  google_polyline_algorithm: ^3.1.0
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
